MODULE NUMERIC_KINDS
  ! 4, 2, AND 1 BYTE INTEGERS
  INTEGER, PARAMETER :: &
       i4b = SELECTED_INT_KIND(9), &
       i2b = SELECTED_INT_KIND(4), &
       i1b = SELECTED_INT_KIND(2)
  ! SINGLE, DOUBLE, AND QUADRUPLE PRECISION
  INTEGER, PARAMETER :: &
       sp = KIND(1.0), &
       dp = KIND(1.0D0), &
       qp = SELECTED_REAL_KIND(2*PRECISION(1.0_dp))
END MODULE NUMERIC_KINDS
